import { useState, type FormEvent, type ReactNode } from 'react';
import { FileText, CheckCircle2, ArrowLeft, Download, PhoneIncoming, ShieldCheck } from 'lucide-react';
import { api, attachment, date, download, shortId, type Workspace, type Case, type LabReport } from '../supervisor';

type Mutation=(path:string,body:unknown,method?:string)=>Promise<void>;
interface Props { data:Workspace; selectedId:string|null; onSelect:(id:string|null)=>void; onMutate:Mutation }
function Form({title,submit,children,onSave}:{title:string;submit:string;children:ReactNode;onSave:(form:FormData)=>Promise<void>}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
 async function handle(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);setError('');setSuccess('');try{await onSave(new FormData(form));form.reset();setSuccess('Saved successfully.')}catch(e){setError(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
 return <form className="workflow-form" onSubmit={handle}><h3>{title}</h3><fieldset disabled={busy}>{children}<button className="primary-button" type="submit">{busy?'Saving…':submit}</button></fieldset>{error&&<p className="form-error" role="alert">{error}</p>}{success&&<p className="save-notice" role="status">{success}</p>}</form>
}
function Field({label,name,type='text',required=true,value,children}:{label:string;name:string;type?:string;required?:boolean;value?:string;children?:ReactNode}){
 return <label className="field"><span>{label}</span>{children?<select name={name} required={required} defaultValue={value}>{children}</select>:type==='textarea'?<textarea name={name} required={required} maxLength={4000} defaultValue={value}/>:<input name={name} type={type} required={required} defaultValue={value} maxLength={500} accept={type==='file'?'application/pdf,image/png,image/jpeg':undefined}/>}</label>
}
const value=(form:FormData,key:string)=>String(form.get(key)||'').trim();
const timestamp=(form:FormData,key:string)=>new Date(value(form,key)).toISOString();
function AttachmentButton({table,id,name}:{table:string;id:string;name:string}){
 const [error,setError]=useState('');return <><button className="text-button" onClick={async()=>{try{await download(`files/${table}/${id}`,name)}catch(e){setError(e instanceof Error?e.message:'Download failed')}}}><Download size={15}/>{name}</button>{error&&<p className="form-error" role="alert">{error}</p>}</>
}
function LabEntry({report,c,onMutate}:{report:LabReport;c:Case;onMutate:Mutation}){
 return <article className="record-entry"><div className="record-heading"><h3>{report.report_number} · {report.lab_name}</h3><span className={`state-badge ${report.verification_status}`}>{report.verification_status==='verified'?'Verified':'Uploaded · unverified'}</span></div><p>{report.result}</p><p className="record-meta">Uploaded {date(report.uploaded_at)} · by {shortId(report.uploaded_by)}</p><AttachmentButton table="lab_reports" id={report.id} name={report.file_name}/><details><summary>File integrity</summary><code className="evidence-hash">SHA-256 {report.file_sha256}</code></details>{report.verification_status==='verified'?<p className="verification-note">Verified {date(report.verified_at)} by {shortId(report.verified_by!)}. {report.verification_note}</p>:c.status!=='closed'&&<Form title="Verify this report" submit="Verify lab report" onSave={async form=>onMutate('rpc/verify_lab_report',{p_report_id:report.id,p_expected_version:c.version,p_note:value(form,'note')})}><p>Review the uploaded document against its source and sample. Uploading alone does not verify it.</p><Field label="Verification findings" name="note" type="textarea"/><label className="check-field"><input type="checkbox" required/>I checked the report, its source, and its sample identity.</label></Form>}</article>
}

export default function SupervisorCasesView({data,selectedId,onSelect,onMutate}:Props){
 const [status,setStatus]=useState('under_review');const [priority,setPriority]=useState('all');const [search,setSearch]=useState('');
 const filtered=data.cases.filter(c=>(status==='all'||c.status===status)&&(priority==='all'||c.priority===priority)&&`${data.water_sources.find(s=>s.id===c.source_id)?.name} ${c.id}`.toLowerCase().includes(search.toLowerCase()));
 const selected=data.cases.find(c=>c.id===selectedId);
 return <div className="supervisor-board"><div className="board-filters"><label>Search cases<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Source name or case ID" type="search"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="under_review">Under review</option><option value="closed">Closed</option></select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">All priorities</option><option value="critical">Critical</option><option value="urgent">Urgent</option><option value="normal">Normal</option></select></label></div>
 <div className={`board-split ${selected?'has-selection':''}`}><section className="board-queue" aria-label="Case queue"><h2>Cases <span>{filtered.length}</span></h2>{filtered.map(c=><button className={`queue-row ${selected?.id===c.id?'selected':''}`} key={c.id} onClick={()=>{onSelect(c.id);if(window.innerWidth>700&&window.innerWidth<=800)requestAnimationFrame(()=>document.querySelector('.case-workspace')?.scrollIntoView({behavior:'smooth',block:'start'}))}} aria-pressed={selected?.id===c.id}><span className="queue-row-meta">{shortId(c.id)}<span className={`state-badge ${c.priority}`}>{c.priority}</span></span><strong>{data.water_sources.find(s=>s.id===c.source_id)?.name||'Water source'}</strong><span className="record-meta">{c.status==='closed'?'Closed':'Under review'} · {c.origin==='ivr'?'Phone complaint':'Field screening'}</span></button>)}{!filtered.length&&<p className="empty-state">No cases match these filters.</p>}</section>{selected?<CaseDetail key={selected.id} c={selected} data={data} onMutate={onMutate} onBack={()=>onSelect(null)}/>:<section className="case-placeholder"><FileText size={30}/><h2>Select a case to review</h2><p>Compare evidence, record follow-up, and inspect the case history.</p></section>}</div>
 <details className="team-submissions"><summary>All team screening records ({data.screening_records.length})</summary><p>Includes every worker in your jurisdiction, including clear submissions without a case.</p>{data.screening_records.map(record=><article className="record-entry" key={record.id}><h3>{record.sample_code} · {data.water_sources.find(s=>s.id===record.source_id)?.name}</h3><p><strong>Machine suggestion:</strong> {record.machine_suggestion}</p><p><strong>Human observation:</strong> {record.human_observation}</p><p className="record-meta">{date(record.captured_at)} · Worker {shortId(record.created_by)}</p>{record.capture_name?<AttachmentButton table="screening_records" id={record.id} name={record.capture_name}/>:<p className="record-meta">No raw capture attachment supplied.</p>}</article>)}</details>
 <section className="ivr-section"><div className="record-heading"><h2><PhoneIncoming size={19}/> Phone-in complaints</h2><span>{data.ivr_complaints.filter(c=>c.status==='new').length} unlinked</span></div>{data.ivr_complaints.map(complaint=><article className="record-entry" key={complaint.id}><h3>Complaint {shortId(complaint.id)}</h3><p>{complaint.summary}</p><p className="record-meta">Received {date(complaint.received_at)} · {complaint.status}</p>{complaint.case_id?<button className="text-button" onClick={()=>{onSelect(complaint.case_id);document.querySelector('.board-split')?.scrollIntoView({behavior:'smooth'})}}>Review linked case {shortId(complaint.case_id)}</button>:<Form title="Link to a case" submit="Link complaint" onSave={async form=>{const selectedCase=data.cases.find(c=>c.id===value(form,'case'))!;await onMutate('rpc/link_ivr_complaint_to_case',{p_complaint_id:complaint.id,p_case_id:selectedCase.id,p_expected_version:selectedCase.version,p_complaint_version:complaint.version},'PATCH')}}><Field label="Open case in this team" name="case"><option value="">Select case</option>{data.cases.filter(c=>c.status!=='closed'&&(!complaint.source_id||c.source_id===complaint.source_id)).map(c=><option key={c.id} value={c.id}>{data.water_sources.find(s=>s.id===c.source_id)?.name} · {shortId(c.id)}</option>)}</Field></Form>}{!complaint.case_id&&<Form title="Or create a case for this complaint" submit="Create and link case" onSave={async form=>onMutate('rpc/create_case_from_ivr',{p_complaint_id:complaint.id,p_complaint_version:complaint.version,p_source_id:value(form,'source')})}><Field label="Reported source" name="source" value={complaint.source_id||''}><option value="">Select source</option>{data.water_sources.filter(s=>!complaint.source_id||s.id===complaint.source_id).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Field></Form>}</article>)}{!data.ivr_complaints.length&&<p className="empty-state">No phone-in complaints in your team.</p>}</section>
 </div>
}
function CaseDetail({c,data,onMutate,onBack}:{c:Case;data:Workspace;onMutate:Mutation;onBack:()=>void}){
 const [tab,setTab]=useState('review');const [auditResult,setAuditResult]=useState('');
 const source=data.water_sources.find(s=>s.id===c.source_id)!;
 const screening=data.screening_records.find(s=>s.id===c.screening_id);
 const labs=data.lab_reports.filter(r=>r.case_id===c.id);const actions=data.case_actions.filter(r=>r.case_id===c.id);const retests=data.retests.filter(r=>r.case_id===c.id);const messages=data.resident_communications.filter(r=>r.case_id===c.id);const audit=data.audit_log.filter(r=>r.entity_id===c.id);
 const eligible=labs.some(r=>r.verification_status==='verified')||retests.some(r=>r.status==='completed'&&r.linked_screening_id);
 const closed=c.status==='closed';const base={case_id:c.id,expected_case_version:c.version};
 return <section className="case-workspace"><button className="text-button mobile-back" onClick={onBack}><ArrowLeft size={16}/>Back to queue</button><header className="case-heading"><p className="record-meta">Case {shortId(c.id)} · Revision {c.version}</p><h2>{source?.name||'Water source'}</h2><p>{source?.locality} · {c.origin==='ivr'?'IVR escalation':'Screening escalation'}</p><span className={`state-badge ${c.status}`}>{closed?'Closed':'Under review'}</span></header><nav className="case-tabs" aria-label="Case sections">{[['review','Evidence'],['labs','Lab reports'],['actions','Actions'],['retests','Retests'],['messages','Residents'],['history','History']].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 <div className="case-tab-content" key={`${c.id}-${c.version}-${tab}`}>
 {tab==='review'&&<><section className="evidence-section"><h3>Machine suggestion</h3><p>{screening?.machine_suggestion||'No original field screening linked to this IVR case.'}</p><small>Screening indication only; not a laboratory confirmation.</small></section><section className="evidence-section"><h3>Worker’s human observation</h3><p>{screening?.human_observation||'No worker observation recorded.'}</p>{screening&&<small>{screening.sample_code} · Captured {date(screening.captured_at)} · Worker {shortId(screening.created_by)}</small>}</section><section className="evidence-section"><h3>Laboratory evidence</h3>{labs.length?labs.map(r=><div key={r.id}><p><strong>{r.report_number}</strong> · {r.result}</p><span className={`state-badge ${r.verification_status}`}>{r.verification_status==='verified'?'Verified':'Uploaded · not verified'}</span></div>):<p>No laboratory report uploaded.</p>}</section><details className="source-details"><summary>Source metadata & team submissions</summary><p>Source {source.id}</p><Form title="Edit source metadata" submit="Save source" onSave={async form=>onMutate(`water_sources?id=eq.${source.id}`,{name:value(form,'name'),locality:value(form,'locality'),version:source.version+1},'PATCH')}><Field label="Source name" name="name" value={source.name}/><Field label="Locality" name="locality" value={source.locality}/></Form><h3>All worker submissions for this source</h3>{data.screening_records.filter(s=>s.source_id===c.source_id).map(s=><div className="record-entry" key={s.id}><strong>{s.sample_code}</strong><p>Machine: {s.machine_suggestion}</p><p>Worker: {s.human_observation}</p><p className="record-meta">{date(s.captured_at)} · {s.screening_flag}</p></div>)}</details><section className="closure-panel"><h3><ShieldCheck size={18}/> Evidence check for closure</h3><ul><li>{labs.some(r=>r.verification_status==='verified')?'Verified lab report available':'No verified lab report'}</li><li>{retests.some(r=>r.status==='completed')?'Completed retest linked':'No completed retest linked'}</li></ul>{closed?<p>Closed {date(c.closed_at)}. {c.closure_reason}</p>:eligible?<Form title="Review and close" submit="Close case with evidence" onSave={async form=>onMutate('rpc/close_case',{p_case_id:c.id,p_expected_version:c.version,p_reason:value(form,'reason')})}><Field label="Closure rationale" name="reason" type="textarea"/><label className="check-field"><input type="checkbox" required/>I reviewed the evidence and the resolution.</label><p>The server rechecks evidence and the case revision before closure.</p></Form>:<><p>A verified lab report <strong>or</strong> a completed, linked retest is required. An upload or a scheduled retest does not qualify.</p><button className="primary-button" disabled>Close case — evidence missing</button></>}</section></>}
 {tab==='labs'&&<>{labs.map(report=><LabEntry key={report.id} report={report} c={c} onMutate={onMutate}/>)}{!labs.length&&<p className="empty-state">No lab reports yet. Upload a document, then verify it separately.</p>}{!closed&&<Form title="Upload laboratory report" submit="Upload report as unverified" onSave={async form=>{const file=form.get('file') as File;await onMutate('lab_reports',{...base,source_id:value(form,'source'),screening_id:value(form,'sample'),report_number:value(form,'number'),lab_name:value(form,'lab'),result:value(form,'result'),...await attachment(file)})}}><div className="form-grid"><Field label="Source printed on the report" name="source" value={c.source_id}>{data.water_sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Field><Field label="Sample printed on the report" name="sample" value={c.screening_id||''}><option value="">Select sample</option>{data.screening_records.filter(s=>s.source_id===c.source_id).map(s=><option key={s.id} value={s.id}>{s.sample_code}</option>)}</Field><Field label="Report number" name="number"/><Field label="Laboratory name" name="lab"/></div><Field label="Laboratory result (as reported)" name="result" type="textarea"/><Field label="Report document · PDF, JPEG or PNG, up to 2 MB" name="file" type="file"/><p>Source and sample mismatches are rejected by the database.</p></Form>}</>}
 {tab==='actions'&&<>{actions.map(a=><article className="record-entry" key={a.id}><span className="state-badge">{a.kind==='referral'?'Lab referral':'Corrective action'}</span><h3>{a.description}</h3><p>{a.performed_by} · {date(a.performed_at)}</p>{a.evidence_name&&<AttachmentButton table="case_actions" id={a.id} name={a.evidence_name}/>}</article>)}{!actions.length&&<p className="empty-state">No referral or corrective action recorded.</p>}{!closed&&<Form title="Record completed action or referral" submit="Record action" onSave={async form=>{const file=form.get('file') as File;const evidence=file?.size?await attachment(file):null;await onMutate('case_actions',{...base,kind:value(form,'kind'),description:value(form,'description'),performed_by:value(form,'by'),performed_at:timestamp(form,'when'),...(evidence?{evidence_name:evidence.file_name,evidence_type:evidence.file_type,evidence_base64:evidence.file_base64}:{})})}}><Field label="Action type" name="kind"><option value="corrective">Corrective action completed</option><option value="referral">Laboratory referral sent</option></Field><Field label="What was done" name="description" type="textarea"/><div className="form-grid"><Field label="Performed by" name="by"/><Field label="Performed at" name="when" type="datetime-local"/></div><Field label="Optional supporting evidence · up to 2 MB" name="file" type="file" required={false}/></Form>}</>}
 {tab==='retests'&&<>{retests.map(r=><article className="record-entry" key={r.id}><div className="record-heading"><h3>Retest {shortId(r.id)}</h3><span className={`state-badge ${r.status}`}>{r.status==='completed'?'Completed · sample linked':'Requested · awaiting sample'}</span></div><p>{r.instructions}</p><p className="record-meta">Requested {date(r.requested_at)} · Due {date(r.due_at)}</p>{r.linked_screening_id?<p>Linked sample: {data.screening_records.find(s=>s.id===r.linked_screening_id)?.sample_code}. Completed {date(r.completed_at)}.</p>:!closed&&<Form title="Link worker’s follow-up sample" submit="Link completed retest" onSave={async form=>onMutate(`retests?id=eq.${r.id}`,{linked_screening_id:value(form,'sample'),expected_case_version:c.version},'PATCH')}><Field label="Later sample from this source" name="sample"><option value="">Select a submitted sample</option>{data.screening_records.filter(s=>s.source_id===c.source_id&&s.id!==c.screening_id&&new Date(s.captured_at)>=new Date(r.requested_at)).map(s=><option key={s.id} value={s.id}>{s.sample_code} · {s.screening_flag}</option>)}</Field><p>If none appear, wait for a worker to submit a follow-up sample. A request is not a completed retest.</p></Form>}</article>)}{!retests.length&&<p className="empty-state">No follow-up requested.</p>}{!closed&&<Form title="Request follow-up sampling" submit="Request retest" onSave={async form=>onMutate('retests',{...base,due_at:timestamp(form,'due'),instructions:value(form,'instructions')})}><Field label="Due date and time" name="due" type="datetime-local"/><Field label="Sampling instructions" name="instructions" type="textarea"/></Form>}</>}
 {tab==='messages'&&<>{messages.map(m=><article className="record-entry" key={m.id}><div className="record-heading"><h3>{m.channel.replace('_',' ')}</h3><span className="state-badge">{m.delivery_status}</span></div><p>{m.message_summary}</p><p className="record-meta">Attempted {date(m.sent_at)} · Reference {m.delivery_reference}</p></article>)}{!messages.length&&<p className="empty-state">No resident communications logged. Delivery is never assumed.</p>}{!closed&&<Form title="Log an actual resident update" submit="Log communication" onSave={async form=>onMutate('resident_communications',{...base,channel:value(form,'channel'),message_summary:value(form,'summary'),sent_at:timestamp(form,'sent'),delivery_status:value(form,'status'),delivery_reference:value(form,'reference')})}><div className="form-grid"><Field label="Channel" name="channel">{['sms','phone','in_person','public_notice','email'].map(v=><option key={v} value={v}>{v.replace('_',' ')}</option>)}</Field><Field label="Delivery status" name="status"><option value="sent">Sent · delivery unconfirmed</option><option value="delivered">Delivered</option><option value="failed">Failed delivery attempt</option></Field></div><Field label="Message summary (avoid personal recipient details)" name="summary" type="textarea"/><div className="form-grid"><Field label="Sent / attempted at" name="sent" type="datetime-local"/><Field label="Dispatch or delivery reference" name="reference"/></div><label className="check-field"><input type="checkbox" required/>This update was actually sent or attempted; it is not a planned message.</label><p>This form records delivery evidence. It does not send a message.</p></Form>}</>}
 {tab==='history'&&<><div className="record-heading"><h3>Case history</h3><button className="secondary-button" onClick={async()=>{try{const result=await api<{valid:boolean}>('rpc/verify_case_audit',{p_case_id:c.id});setAuditResult(result.valid?'Hash chain verified.':'Integrity check failed. Contact your administrator.')}catch(e){setAuditResult(e instanceof Error?e.message:'Unable to verify history')}}}><CheckCircle2 size={16}/>Verify history</button></div><p className="record-meta">Append-only events with linked SHA-256 hashes. This detects changed entries; it is not an external notarization.</p>{auditResult&&<p role="status">{auditResult}</p>}<ol className="audit-timeline">{audit.map(entry=><li key={entry.id}><h4>{entry.event.replaceAll('_',' ').replace('.',' · ')}</h4><p>{date(entry.occurred_at)} · {entry.actor_id?shortId(entry.actor_id):'System'}</p><details><summary>Event record {entry.sequence}</summary><pre>{JSON.stringify(entry.payload,null,2)}</pre><code className="evidence-hash">{entry.event_hash}</code></details></li>)}</ol></>}
 </div></section>
}
